# Generated by Django 3.2 on 2023-04-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('vetements', 'vetements'), ('chaussures', 'chaussures'), ('tshirt', 'tshirt')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
