# Generated by Django 3.2 on 2023-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230506_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
